version: '2.1'
services:
  dev:
    build: .
    user: ${DEV_USER_ID:-1000}
    working_dir: /code
    environment:
      HOME: /home/dev
      PATH: /home/dev/.local/bin:/usr/bin
      GREENWAVE_TEST_URL: http://dev:8080/
      WAIVERDB_TEST_URL: http://waiverdb:5004/
      RESULTSDB_TEST_URL: http://resultsdb:5001/
      PYTEST_ADDOPTS: "-o cache_dir=/home/dev/.pytest_cache"
    command:
      - "/bin/bash"
      - "-c"
      - |
        set -e

        # Check if UID is same as owner of the mounted home directory
        # (avoids creating files with wrong owner).
        real_dev_id="$$(stat --format %u ~)"
        if [[ $$real_dev_id != $$UID ]]; then
            echo "Set correct DEV_USER_ID in .env file (should be same as owner of docker/home)."
            exit 1
        fi

        exec /usr/bin/gunicorn-3 \
          --reload \
          --bind=0.0.0.0:8080 \
          --access-logfile=- \
          --enable-stdio-inheritance \
          greenwave.wsgi:app
    volumes:
      - ./:/code:ro,z
      - ../waiverdb:/waiverdb:ro,z
      - ../resultsdb:/resultsdb:ro,z
      - ./docker/home:/home/dev:Z
      - ./docker/greenwave-settings.py:/etc/greenwave/settings.py:ro,z
      - ./conf/policies/:/etc/greenwave/policies/:ro,z
    ports:
      - 8080:8080
    depends_on:
      - memcached
      - resultsdb
      - waiverdb

  resultsdb-db:
    image: postgres:9.5.2
    restart: always
    environment:
      POSTGRES_USER: resultsdb
      POSTGRES_PASSWORD: resultsdb
      POSTGRES_DB: resultsdb
      POSTGRES_INITDB_ARGS: "--auth='ident' --auth='trust'"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  resultsdb:
    build:
      context: ../resultsdb
      dockerfile: openshift/Dockerfile
    command:
      - "/bin/bash"
      - "-c"
      - |
        set -e
        resultsdb init_db
        exec mod_wsgi-express-3 start-server /usr/share/resultsdb/resultsdb.wsgi \
            --user apache --group apache \
            --port 5001 --threads 5 \
            --include-file /etc/httpd/conf.d/resultsdb.conf \
            --log-level info \
            --log-to-terminal \
            --access-log \
            --startup-log
    volumes:
      - ./docker/resultsdb-settings.py:/etc/resultsdb/settings.py:ro,z
      - ./docker/resultsdb.conf:/etc/httpd/conf.d/resultsdb.conf:ro,z
    ports:
      - 5001:5001
    depends_on:
      resultsdb-db:
        condition: service_healthy

  waiverdb-db:
    image: postgres:9.5.2
    restart: always
    environment:
      POSTGRES_USER: waiverdb
      POSTGRES_PASSWORD: waiverdb
      POSTGRES_DB: waiverdb
      POSTGRES_INITDB_ARGS: "--auth='ident' --auth='trust'"

  waiverdb:
    image: "quay.io/factory2/waiverdb:latest"
    working_dir: /code
    environment:
      DATABASE_PASSWORD: waiverdb
      SECRET_KEY: waiverdb
    command:
      - "/bin/bash"
      - "-c"
      - |
        set -e
        python3 waiverdb/manage.py wait-for-db
        python3 waiverdb/manage.py db upgrade
        exec /usr/bin/gunicorn-3 \
          --reload \
          --bind=0.0.0.0:5004 \
          --access-logfile=- \
          --enable-stdio-inheritance \
          waiverdb.wsgi:app
    volumes:
      - ../waiverdb:/code:ro,z
      - ./docker/waiverdb-settings.py:/etc/waiverdb/settings.py:ro,z
      - ./docker/client_secrets.json:/etc/secret/client_secrets.json:ro,z
    ports:
     - 5004:5004
    user: '0'
    depends_on:
      - waiverdb-db

  memcached:
    image: "docker.io/modularitycontainers/memcached"

networks:
  default:
    driver: bridge
