---
server:
  address: 0.0.0.0
  port: 8081
management:
  security.enabled: false
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: "*"
  health:
    jms.enabled: false
    amq.enabled: true
    ldap.enabled: false
umb:
  ldap:
    embedded:
      enabled: false
  amq:
    broker:
      plugins:
        enableLdapBackedAuthentication: false
        enableLdapBackedAuthorization: false
        enablePlatformSecurityAuthorizationBroker: false
        enablePlatformLibraryAuthentication: false
        enablePlatformLibraryAuthorization: false
      transportConnectors:
      - amqp://0.0.0.0:5671?transport.maximumConnections=2500&transport.needClientAuth=false&transport.transformer=jms&wireFormat.allowNonSaslConnections=true&transport.closeAsync=false&transport.daemon=true&wireFormat.maxInactivityDurationInitalDelay=60000&wireFormat.maxInactivityDuration=60000
      - stomp://0.0.0.0:61612?transport.maximumConnections=2500&transport.needClientAuth=false&transport.closeAsync=false&transport.daemon=true&wireFormat.maxInactivityDurationInitalDelay=60000&wireFormat.maxInactivityDuration=60000
logging:
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
  path: /var/log/umb
  file.max-size: 10MB
  file.max-history: 50
logback.access:
  enabled: false
